#!/bin/bash

# Inisialisasi variabel
stopwords=""                                                    
kata=""
# Mengambil argumen dengan flag
while getopts "s:","t:" opt; do                                   
case $opt in
    s)
      stopwords="$OPTARG"
      ;;
    t)
      kata="$OPTARG"
      ;;
    *)
      echo "Usage: ./BashTextMiner -s <stopwords_file> -t <jumlah kata> <namafile.txt>"
      exit 1                                                          
;;
  esac
done                                                            
# Geser argumen untuk mendapatkan file teks
shift "$((OPTIND-1))"
# Memeriksa jumlah argumen yang diberikan
if [ "$#" -ne 1 ]; then                                           
echo "Usage: ./BashTextMiner -s <stopwords_file> -t <jumlah kata>§<namafile.txt >"
  exit 1
fi

# File teks yang akan diproses
file_path="$1"                                                  
# Memeriksa apakah file stopwords telah disediakan
if [ -z "$stopwords" ]; then
  echo "Gunakan opsi -s untuk menyediakan file stopwords."
  exit 1
fi

# Memeriksa apakah file stopwords tersedia
if [ ! -f "$stopwords" ]; then
  echo "File stopwords '$stopwords' tidak ditemukan."
  exit 1
fi


# Memeriksa apakah file jumlah kata  telah disediakan
if [ -z "$kata" ]; then
  echo "Gunakan opsi -t untuk jumlah kata."
  exit 1
fi

# Menghapus kata-kata yang ada di stopwords dari teks
filtered_words=$(tr -sc 'A-Za-z' '\n' < "$file_path" | tr '[:upper:]' '[:lower:]' | sort | uniq -c | sort -nr | grep -v -w -f "$stopwords")

# Ambil 400 kata yang paling sering muncul
top_words=$(echo "$filtered_words" | head -n "$kata")

# Menampilkan hasil
echo -e "$top_words"
