#!/bin/bash

# Inisialisasi variabel
stopwords=""

# Mengambil argumen dengan flag
while getopts "s:" opt; do
  case $opt in
    s)
      stopwords="$OPTARG"
      ;;
    *)
      echo "Usage: . /skrip.sh -s <stopwords_file> <namafile.txt>"
      exit 1
      ;;
  esac
done

# Geser argumen untuk mendapatkan file teks
shift "$((OPTIND-1))"

# Memeriksa jumlah argumen yang diberikan
if [ "$#" -ne 1 ]; then
  echo "Usage: . /skrip.sh -s <stopwords_file> <namafile.txt>"
  exit 1
fi

# File teks yang akan diproses
file_path="$1"

# Memeriksa apakah file stopwords telah disediakan
if [ -z "$stopwords" ]; then
  echo "Gunakan opsi -s untuk menyediakan file stopwords."
  exit 1
fi

# Memeriksa apakah file stopwords tersedia
if [ ! -f "$stopwords" ]; then
  echo "File stopwords '$stopwords' tidak ditemukan."
  exit 1
fi

# Menghapus kata-kata yang ada di stopwords dari teks
filtered_words=$(tr -sc 'A-Za-z' '\n' < "$file_path" | tr '[:upper:]' '[:lower:]' | sort | uniq -c | sort -nr | grep -v -w -f "$stopwords")

# Ambil 400 kata yang paling sering muncul
top_words=$(echo "$filtered_words" | head -n 400)

# Menampilkan hasil
echo -e "$top_words"
